// One primary series per featured card face; images remain in examples/ for Pages and GitHub.
export const seriesNames = {
  art: "艺术风格",
  modern: "现代设计",
  pokemon: "宝可梦",
  city: "城市",
  anime: "二次元",
  meme: "玩梗",
};

export const works = [
  { id: "post-impressionist-visa", title: "旋涡夜景", subtitle: "后印象派 × Visa", series: "art", image: "post-impressionist-visa.png", prompt: "使用 card-creator Skill，生成一张深蓝旋涡夜空的后印象派卡面，右下角哑金 Visa。" },
  { id: "mucha-art-nouveau-octopus", title: "新艺术花卉", subtitle: "复古纸感 × 八达通", series: "art", image: "mucha-art-nouveau-octopus.png", prompt: "使用 card-creator Skill，生成一张穆夏新艺术风格卡面：花卉人物、复古纸感，右下角古铜色八达通。" },
  { id: "chatgpt-gardevoir-cmb-unionpay", title: "超能系粉色", subtitle: "沙奈朵 × 招商银行 × 银联", series: "pokemon", image: "chatgpt-gardevoir-cmb-unionpay.png", origin: "用户分享的 ChatGPT 网页成图；无法确认当时是否加载了 Skill。", prompt: "使用 [juju-w/card-creator-skill](https://github.com/juju-w/card-creator-skill) card-creator Skill @创建图像 ，生成一张宝可梦里沙奈朵的卡面，简洁，超能系粉色， 招商银行银联信用卡，不要芯片" },
  { id: "greater-bay-sea-bridge-concept", title: "大湾区 · 海上相连", subtitle: "海桥潮汐 × 大湾区通概念标志 × 交通联合", series: "city", image: "greater-bay-sea-bridge-concept.png", origin: "「大湾区通」是虚构的艺术概念标志；交通联合为 AI 风格化描绘，并非官方标志文件。本图不是已发行卡，也不表示可在任何地区互通。", prompt: "使用 card-creator Skill，生成一张大湾区海桥概念卡面：珍珠色晨光、群岛和跨海大桥，左上角自创「大湾区通」概念标志，右下角交通联合；不代表实际发行或通刷。" },
  { id: "niu-lai-amex-parody", title: "牛来 · 运通肖像", subtitle: "抽象电影梗 × American Express", series: "meme", image: "niu-lai-amex-parody.png", origin: "非官方恶搞二创；牛来形象和 American Express 标志均为 AI 风格化描绘，不是电影或品牌授权卡面。", prompt: "使用 card-creator Skill，生成一张《牛来》× American Express 玩梗卡面：把经典运通肖像换成主角小牛牛来，保留它的斜眼和紫色牛鼻，蓝金雕版质感，不要芯片、卡号或感应标志。" },
  { id: "hsbc-crystal-cat", title: "蓝晶猫影", subtitle: "折面猫咪 × 汇丰", series: "modern", image: "hsbc-crystal-cat.png", prompt: "使用 card-creator Skill，生成一张汇丰风格卡面：深蓝晶面中坐着一只优雅的猫，弯曲的尾巴融入几何背景，右上角汇丰标志；不要狮子、芯片或多余文字。" },
  { id: "monet-water-lilies-visa", title: "睡莲印象派", subtitle: "珠光水面 × Visa", series: "art", image: "monet-water-lilies-visa.png", prompt: "使用 card-creator Skill，生成一张睡莲印象派卡面：蓝紫水面、少量珠光，右下角银白 Visa。" },
  { id: "klimt-gold-mastercard", title: "金箔装饰画", subtitle: "旋涡枝蔓 × Mastercard", series: "art", image: "klimt-gold-mastercard.png", prompt: "使用 card-creator Skill，生成一张金箔装饰画卡面：旋涡枝蔓、宝石色点缀，右下角金线 Mastercard。" },
  { id: "morandi-still-life-wise", title: "莫兰迪静物", subtitle: "灰粉陶器 × WISE", series: "modern", image: "morandi-still-life-wise.png", alternate: "morandi-still-life.png", prompt: "使用 card-creator Skill，生成一张莫兰迪风格的三件陶器静物卡面：灰粉、燕麦与鼠尾草绿，右下角加低调的 WISE 字标。" },
  { id: "apple-cash-iridescent-ribbon", title: "虹彩流线", subtitle: "黑曜石 × Apple Cash", series: "modern", image: "apple-cash-iridescent-ribbon-opaque.png", prompt: "使用 card-creator Skill，生成一张 Apple Cash 风格卡面：黑曜石底色、一条薄荷银紫色虹彩丝带，右下角白色 Apple Cash 标志，极简且不要芯片。" },
  { id: "hokusai-wave-suica", title: "浮世绘海浪", subtitle: "远山与浪 × Suica", series: "art", image: "hokusai-wave-suica.png", prompt: "使用 card-creator Skill，生成一张浮世绘海浪与远处富士山的卡面，右下角深蓝 Suica。" },
  { id: "song-blue-green-unionpay", title: "青绿山水", subtitle: "矿物色与云母 × 银联", series: "art", image: "song-blue-green-unionpay.png", prompt: "使用 card-creator Skill，生成一张宋画青绿山水卡面：矿物颜料、云母云雾，右下角金蓝风格化银联。" },
  { id: "vienna-secession-diners", title: "维也纳分离派", subtitle: "黑金人物 × Diners Club", series: "art", image: "vienna-secession-diners.png", prompt: "使用 card-creator Skill，生成一张维也纳分离派风格的黑金高级艺术卡面，右下角哑金 Diners Club。" },
  { id: "chatgpt-metagross-icbc-mastercard-world", title: "青色云母金属", subtitle: "巨金怪 × 工商银行 × Mastercard", series: "pokemon", image: "chatgpt-metagross-icbc-mastercard-world.png", origin: "用户分享的 ChatGPT 网页成图；原始 Prompt 中的 word 保持原样，无法确认当时是否加载了 Skill。", prompt: "@创建图像 使用 [juju-w/card-creator-skill](https://github.com/juju-w/card-creator-skill) card-creator Skill  ，生成一张宝可梦里巨金怪的万事达 word 卡面，工商银行，不要芯片，万事达logo 不要颜色只保留线条，整体有云母/金属光泽，保持青色系" },
  { id: "gemini-magikarp-icoca", title: "水边的鲤鱼王", subtitle: "简洁海蓝 × ICOCA", series: "pokemon", image: "gemini-magikarp-icoca.jpeg", origin: "用户分享的 Gemini 成图；标志为生成图里的非官方诠释。", prompt: "使用 card-creator Skill，生成一张鲤鱼王 × ICOCA 卡面：简洁，右下角 ICOCA。" },
  { id: "gemini-gengar-octopus", title: "紫色耿鬼", subtitle: "夜色科技 × 八达通", series: "pokemon", image: "gemini-gengar-octopus.jpeg", origin: "用户分享的 Gemini 成图；紫色标志为生成图里的非官方诠释。", prompt: "使用 card-creator Skill，生成一张耿鬼 × 八达通卡面，让八达通 Logo 变成与画面匹配的紫色。" },
  { id: "chiikawa-suica", title: "四叶草草地", subtitle: "清新水彩 × Suica", series: "anime", image: "chiikawa-suica.png", prompt: "使用 card-creator Skill，生成一张清新水彩风 Chiikawa × Suica 卡面，右下角 Suica。" },
  { id: "laughing-nailong-suica", title: "奶龙捧腹大笑", subtitle: "抽象表情包 × 黄色 Suica", series: "meme", image: "laughing-nailong-suica.png", origin: "非官方恶搞二创；使用奶龙捧腹大笑表情包作姿势参考，Suica 标志由 AI 风格化描绘，不是授权交通卡。", prompt: "使用 card-creator Skill，做一张黄色版西瓜卡：保留经典斜切版式，把企鹅换成那个闭眼张嘴、双手捧腹大笑的抽象奶龙表情包；只保留 Suica，不要芯片、卡号或感应标志。" },
  { id: "huashan-ink-tunion", title: "华山水墨", subtitle: "山水留白 × 交通联合", series: "art", image: "huashan-ink-tunion.png", prompt: "使用 card-creator Skill，生成一张华山水墨画风格的交通卡面，右下角交通联合。" },
  { id: "guangzhou-arcade-yangchengtong", title: "广州 · 彩窗夜河", subtitle: "骑楼彩窗 × 羊城通", series: "city", image: "guangzhou-arcade-yangchengtong.png", prompt: "使用 card-creator Skill，生成一张广州羊城通卡面：骑楼彩窗框住黄昏的广州塔和珠江，孔雀蓝、珊瑚橙与珐琅质感，不要芯片或其他标志。" },
  { id: "foshan-lion-dance-guangfo-tong", title: "佛山 · 赤金醒狮", subtitle: "剪纸漆艺 × 广佛通", series: "city", image: "foshan-lion-dance-guangfo-tong.png", prompt: "使用 card-creator Skill，生成一张佛山广佛通卡面：赤金剪纸漆艺风的醒狮，右侧保留广佛通标志，不要芯片或额外文字。" },
  { id: "palace-museum-cranes-unionpay", title: "北京 · 故宫典藏", subtitle: "云母祥云与仙鹤", series: "city", image: "palace-museum-cranes-unionpay.png", prompt: "使用 card-creator Skill，生成一张北京故宫典藏风卡面，使用云母祥云、仙鹤、宫殿和哑金风格化标志。" },
  { id: "shanghai-art-deco-unionpay", title: "上海装饰艺术", subtitle: "外滩扇面 × 深翡翠银联", series: "city", image: "shanghai-art-deco-unionpay-v2.png", prompt: "使用 card-creator Skill，生成一张上海装饰艺术卡面：深翡翠底、古金扇面、外滩钟楼与江面倒影，右下角哑金短款银联。" },
  { id: "xian-changan-tong-bell-tower", title: "西安 · 石色钟楼", subtitle: "暖石细线 × 长安通", series: "city", image: "xian-changan-tong-bell-tower.png", prompt: "使用 card-creator Skill，生成一张西安长安通卡面：暖石色留白、陶红与石板蓝细线钟楼，左上角长安通标志，不要芯片或额外文字。" },
  { id: "shenzhen-bay-tong-symbol", title: "深圳 · 海湾流线", subtitle: "浅青海湾 × 深圳通符号", series: "city", image: "shenzhen-bay-tong-symbol.png", prompt: "使用 card-creator Skill，生成一张深圳通卡面：浅青极简、海湾大桥与滨海天际线，左上角放小号深圳通图形符号，不加字。" },
  { id: "hangzhou-west-lake-citizen-card", title: "杭州 · 西湖瓷青", subtitle: "断桥荷叶 × 市民卡运营方", series: "city", image: "hangzhou-west-lake-citizen-card.png", origin: "AI 风格化创作示例；参考图是杭州市民卡运营方标志，不是已核实的杭州通卡种贴纸。", prompt: "使用 card-creator Skill，生成一张杭州西湖卡面：瓷青色、断桥、柳叶与荷花，右上角杭州市民卡运营方标志；不要写杭州通。" },
  { id: "chongqing-city-card-monorail", title: "重庆 · 山城轨道", subtitle: "穿楼单轨 × 城市通卡运营方", series: "city", image: "chongqing-city-card-monorail.png", origin: "AI 风格化创作示例；参考图是重庆城市通卡运营方标志，不是已核实的畅通卡卡种贴纸。", prompt: "使用 card-creator Skill，生成一张重庆山城轨道卡面：蓝调夜色、穿楼单轨与江岸层叠，左上角重庆城市通卡运营方标志，不要虚构其他字样。" },
  { id: "minimal-mastercard", title: "一笔成线", subtitle: "暖象牙白 × Mastercard", series: "modern", image: "minimal-mastercard.png", prompt: "使用 card-creator Skill，生成一张暖象牙白的极简线条 Mastercard 卡面，右下角 Mastercard。" },
];
