#!/usr/bin/env python3
"""Build the single-file web guide from the installed Skill's canonical text."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills" / "card-creator" / "SKILL.md"
RULES = ROOT / "skills" / "card-creator" / "references" / "card-rules.md"
OUTPUT = ROOT / "web" / "card-creator.md"
REFERENCE_INDEX = (
    "https://raw.githubusercontent.com/juju-w/card-creator-skill/main/"
    "skills/card-creator/references/logo-reference-index.md"
)
INSTALLED_LOGO_ROUTING = (
    "When a logo is named, find it in the [picture index]"
    "(references/logo-reference-index.md) and pass only its relevant picture(s) "
    "to image generation. Prefer the user's attached reference. If unavailable, "
    "use model knowledge; search only when requested or identification is "
    "genuinely uncertain. Do not audit the library or read source histories "
    "to make a card."
)
WEB_LOGO_ROUTING = (
    "When a logo is named, prefer the user's uploaded reference. Otherwise "
    "use model knowledge; only if the mark is genuinely uncertain and web "
    "access works, open its relevant picture from the "
    f"[optional picture index]({REFERENCE_INDEX}). "
    "Do not scan the whole library or delay image generation for research."
)


def without_frontmatter(content: str) -> str:
    if not content.startswith("---\n"):
        raise ValueError(f"{SKILL} is missing YAML frontmatter")
    marker = "\n---\n"
    end = content.find(marker, 4)
    if end < 0:
        raise ValueError(f"{SKILL} has unfinished YAML frontmatter")
    return content[end + len(marker) :].strip()


def build_text() -> str:
    workflow = without_frontmatter(SKILL.read_text(encoding="utf-8"))
    if not workflow.startswith("# Card Creator\n"):
        raise ValueError("unexpected Skill heading")
    if INSTALLED_LOGO_ROUTING not in workflow:
        raise ValueError("installed logo routing changed; review the web variant")
    workflow = workflow.replace("# Card Creator\n", "## Workflow\n", 1)
    workflow = workflow.replace(INSTALLED_LOGO_ROUTING, WEB_LOGO_ROUTING, 1)
    workflow = workflow.replace("(references/card-rules.md)", "(#card-rules)")

    rules = RULES.read_text(encoding="utf-8").strip()
    if not rules.startswith("# Card rules\n"):
        raise ValueError("unexpected card-rules heading")
    rules = rules.replace("# Card rules\n", "## Card rules\n", 1)

    return (
        "<!-- Generated by packaging/build_web_md.py from "
        "skills/card-creator/SKILL.md and its card-rules.md. Do not edit here. -->\n\n"
        "# Card Creator · Web image guide\n\n"
        "请在网页聊天中先选择图片生成功能，再让模型读取本文件。"
        "这是公开的单文件提示指南，不代表 Skill 已安装。"
        "如果当前界面无法读取链接，请上传本文件。\n\n"
        "Use the available image-generation tool for the finished card. "
        "This page contains the complete workflow and card rules; "
        "follow any uploaded visual references for the requested design. "
        "The optional logo picture index is only for a mark whose appearance needs checking.\n\n"
        f"{workflow}\n\n{rules}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed web guide differs from the canonical sources",
    )
    args = parser.parse_args()
    expected = build_text()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            parser.error(f"{OUTPUT} is missing or stale; regenerate it")
        print(f"Up to date: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Built: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
