#!/usr/bin/env python3
"""Build the single-file web guide from the installed Skill's canonical text."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from skill_text import ROOT, card_rules, workflow

OUTPUT = ROOT / "web" / "card-creator.md"
REFERENCE_INDEX = (
    "https://raw.githubusercontent.com/juju-w/card-creator-skill/main/"
    "skills/card-creator/references/logo-reference-index.md"
)


def build_text() -> str:
    body = workflow().replace("# Card Creator\n", "## Workflow\n", 1)
    body = body.replace("(references/card-rules.md)", "(#card-rules)")
    body = body.replace("(references/logo-reference-index.md)", f"({REFERENCE_INDEX})")
    rules = card_rules().replace("# Card rules\n", "## Card rules\n", 1)

    return (
        "<!-- Generated by packaging/build_web_md.py from "
        "skills/card-creator/SKILL.md and its card-rules.md. Do not edit here. -->\n\n"
        "# Card Creator · Web image guide\n\n"
        "请在网页聊天中先选择图片生成功能，再让模型读取本文件。"
        "这是公开的单文件提示指南，不代表 Skill 已安装。"
        "如果当前界面无法读取链接，请上传本文件。\n\n"
        "Use the available image-generation tool for the finished card. "
        "This page contains the complete workflow and card rules; "
        "follow any uploaded visual references for the requested design. "
        "The optional logo picture index is only for a mark whose appearance needs checking.\n\n"
        f"{body}\n\n{rules}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed web guide differs from the canonical sources",
    )
    args = parser.parse_args()
    expected = build_text()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            parser.error(f"{OUTPUT} is missing or stale; regenerate it")
        print(f"Up to date: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Built: {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
